apiVersion: v1
kind: Service
metadata:
  name: my-notes-app-service
  namespace: my-notes-app
spec:
  type: NodePort
  selector:
    app: my-notes-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
      
      
